---
- hosts: db
  become: yes

  vars:
    db_name: "DATABASE_NAME"
    postgres_db_port: PG_PORT

  tasks:
    - name: "Create a backup directory"
      file:
        path: "/tmp/backups/"
        mode: 0777
        owner: postgres
        state: directory
    
    - name: "Back up the database"
      postgresql_db:
        state: dump
        name: "{{ db_name }}"
        port: "{{ postgres_db_port | 5432 }}"
        target: "/tmp/backups/{{ ansible_date_time.date }}_{{ db_name }}.dump"
    #   become: yes
      become_user: postgres

    - name: "Fetch backup from the server"
      fetch:
        src: "/tmp/backups/{{ ansible_date_time.date }}_{{ db_name }}.dump"
        dest: "~/{{ ansible_date_time.date }}_{{ db_name }}.dump"
        flat: yes